version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Use MongoDB Atlas connection string
      DATABASE_URL: mongodb+srv://username:password@cluster.mongodb.net/surgery-management?retryWrites=true&w=majority
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-super-secret-jwt-key-change-this-in-production-at-least-32-chars
    volumes:
      - ./prisma:/app/prisma

# Note: MongoDB is now hosted on Atlas, no local database container needed

